### ISSUE TITLE
is there a way to re encode a video dropping the audio?

### ISSUE THREAD

**Issue by sathio** [PHP-FFMpeg/PHP-FFMpeg#142]
Hi, on the Readme it is mentioned that is possible to isolate video or audio, but I didn't find any way to do this. I'd like to remove audio from a video, the equivalent of "-an" on the raw command to ffmpeg.

cheers

**Comment by DavidDomain** [comment]
Try the following.
First create your own video format like it is described in the readme file or by coping an existing video format. Then add the get extra params method to your custom format like so:
```php

    public function getExtraParams()
    {
        return array('-an');
    }

```
You can find this method in the DefaultAudio abstract class. Since DefaultVideo extends DefaultAudio this should work just fine. This is what the docs are saying:

```php
array()	getExtraParams()
//Returns an array of extra parameters to add to ffmpeg commandline.
```
I tested this by adding the above to the X264 format and it worked for me, but i would not recommend to add this to an existing format.

**Comment by Romain** [comment]
See issue #262 and PR #215.
