### ISSUE TITLE
Can get current file size from Progress Listener

### ISSUE THREAD

**Issue by QuentinLORIOT** [PHP-FFMpeg/PHP-FFMpeg#158]
Hello,

From the progress listener, we can get percentage, remaining time and rate of encoding. 

I saw many other attributes which they could be convenient into the class AbstractProgressListener.php, like the Current File Size.

I tested to use these others attributes and I just had to put a new element with the attribute wanted into the array returned by the method getProgressInfo (in AbstractProgressListener.php).

It would be nice to integrate it ! 

Thank you :)

**Comment by ivan0013** [comment]
Hi, I know this is not the best place to post this, but I need some tips using this plugin. I want to create a progress bar, so for me is enough getting the percentage of the conversion. How did you do to retrieve it? I have tried this piece of code:

$format->on('progress', function ($video, $format, $percentage) {
        echo "$percentage % transcoded";
    });

It works, but I need to put it in a function to call it via $ajax and refresh the progress bar. I don't know how to do that because it is using the event handler. Then I your question, about using the ProgressListener, but I can't retrieve the data, it is always 0, in spite of the conversion is fine. 

So could you tell me how to retrieve the info about percentage using the ProgressListener, or other way to get the percentage via $ajax?

Thank you very much!

**Comment by QuentinLORIOT** [comment]
Hi Ivan,

Your piece of code is good.

When I want to start an encoding, I put a flag into my database to notify a daemon script to run the encoding for the video downloaded, so it's a server thread which are used.
Then during the encoding I put the progress data into the database, with something like this:

$format->on('progress', function ($video, $format, $percentage) {
      <Here I update the field corresponding to my video with percentage>
});

For getting the progress data in "real time" I use an ajax calling which it get data from database. So the thread used is this one used by the user connected to the website.

Hoping that help you :)

**Comment by ivan0013** [comment]
Thanks. This is a very useful info. I haven't thought about the possibility of storing the % on the DB and then read it.

**Comment by patkar** [comment]
@QuentinLORIOT If you know what to do, please create a Pull Request.

@ivan0013 If you have generel questions about the usage which is not a bug, please ask them on http://stackoverflow.com/questions/tagged/php-ffmpeg
