### ISSUE TITLE
Disable subtitles

### ISSUE THREAD

**Issue by Ortix92** [PHP-FFMpeg/PHP-FFMpeg#171]
I'm taking a lot of screenshots (extracting frames) from videos (anime) using PHP-FFMpeg but some videos automatically decode the subtitles. Any way to forcefully disable the subtitles and not render them?

**Comment by patkar** [comment]
@Ortix92 Do you know how is this done with ffmpeg itself? If yes, please tell us and be detailed and specific.

**Comment by Ortix92** [comment]
@patkar unfortunately I don't know. I have stopped developing my application for now. You can find it here: https://github.com/Ortix92/torshot

**Comment by patkar** [comment]
May you research please?

**Comment by Romain** [comment]
For now, I would recommand to use the new additionalParams filter to pass the "-sn" option.
I wouldn't guarantee it will work, but refering to [this section](https://www.ffmpeg.org/ffmpeg.html#Subtitle-options) of the doc, my guess is that it's the proper option.
Since your project is on hold and you didn't provided more information on how to do this with the command line, I'll close this issue for now.
