### ISSUE TITLE
[PROPOSAL] Checking for binary pre-install

### ISSUE THREAD

**Issue by underparnv** [PHP-FFMpeg/PHP-FFMpeg#195]
Thought about using a method similar to that outlined in http://stackoverflow.com/a/25062884/4276640 to check for the requisite binaries before installation.

If unable to locate them, ask for a config file to be made with the path(s), perhaps?

Just bouncing an idea around to see if there is interest in an implementation of this since requiring this library into your project requires the use of the binary.

Thoughts?

**Comment by patkar** [comment]
The stackoverflow answer misses one topic. Composer hooks are only executed on the root package. If you add those to PHP-FFMPeg, they have no effect. You have to mention them in in the install docs. Not the best usability improvement to now. Especially, where to write the config file?

How about Symfony, Laravel and others frameworks who have their own way to configure stuff? This would conflict.

How about sysadmin who don't want auto-detection, because they ship their own binaries (self compiled)?

**Comment by patkar** [comment]
The underlying library `AlchemyDriver`, which handles the communication with the binary itself, does a limited auto-discovery of the binaries already if not supplied by configuration.
