### ISSUE TITLE
ffmpeg-php gd support	disabled

### ISSUE THREAD

**Issue by realone09** [PHP-FFMpeg/PHP-FFMpeg#214]
Hi

i am unable enable ffmpeg-php gd support .all are there in very correct . but not able to enable

| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by patkar** [comment]
Hi @realone09!

Sadly your issue is very unclear to me. The php gd extension has nothing to do with the lib and IRC PHP-FFmpeg doesn't use GD functions. Another point, ffmpeg-php is not PHP-FFmpeg. ffmpeg-php is an outdated php extension and is not this repository. Please look closer before spamming repos. :smiling_imp: 

And please, for the next time you create a issue on GitHub, if you are presented a issue template please fill it out and don't write your stuff above! :smiley:
