### ISSUE TITLE
Call to undefined method FFMpeg\Filters\Video\VideoFilters::getExtraParams()

### ISSUE THREAD

**Issue by Tinywan** [PHP-FFMpeg/PHP-FFMpeg#278]
$ffmpeg = FFMpeg::create([
            'ffmpeg.binaries' => 'd:\ffmpeg\bin\ffmpeg.EXE',
            'ffprobe.binaries' => 'd:\ffmpeg\bin\ffprobe.exe',
            'timeout' => 3600,
            'ffmpeg.threads' => 12,
        ]);
        $MP4Path = 'F:\Tinywan\Video\fooimage2.avi';
        $watermarkPath = 'F:\Tinywan\Video\00018.jpg';
        $video = $ffmpeg->open($MP4Path);
        $watermark = $video->filters()->watermark($watermarkPath, array(
                'position' => 'relative',
                'bottom' => 50,
                'right' => 50,
            ));
        // Extract the image into a new file
        $video->save($watermark,'fooimage2_Watermark.avi');
        var_dump($video);

**Comment by Romain** [comment]
@Tinywan, we're here to help, but we're all volunteers. There are some rules to respect when posting here.

When you create an issue, you have a layout which is provided which intend to help us understand what you're trying to do, and what is the problem you're facing. Copy-pasting piece of codes everywhere is of no help. I'm not gonna answer this issue until you fulfill correctly the layout below.

If you're uncomfortable reproducing it in a comment, please close this issue and create a new one.

<hr>

| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.
