### ISSUE TITLE
Error when saving video with big(maybe) file size

### ISSUE THREAD

**Issue by webfreaks** [PHP-FFMpeg/PHP-FFMpeg#288]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.7.0
| FFmpeg Version | git-2016-11-26-99ee8ee
| OS             | CentOS 7

Hai,

I got some problem when saving a video to mp4 with size above 1Mb.
I try give a video with under 100Kb size an overlay and save to *.mp4 and it's working properly. 
But, when the video above 1Mb I got an error like this.

Debug log:
```
[ERROR] ffmpeg version git-2016-11-26-99ee8ee
[ERROR] Copyright (c) 2000-2016 the FFmpeg developers
[ERROR] built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-4)
[ERROR] configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/usr/local/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265
[ERROR] libavutil 55. 41.101 / 55. 41.101
[ERROR] libavcodec 57. 66.108 / 57. 66.108
[ERROR] libavformat 57. 58.101 / 57. 58.101
[ERROR] libavdevice 57. 2.100 / 57. 2.100
[ERROR] libavfilter 6. 67.100 / 6. 67.100
[ERROR] libswscale 4. 3.101 / 4. 3.101
[ERROR] libswresample 2. 4.100 / 2. 4.100
[ERROR] libpostproc 54. 2.100 / 54. 2.100
[ERROR] Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video_source2.mp4':
[ERROR] Metadata:
[ERROR] major_brand : isom
[ERROR] minor_version : 512
[ERROR] compatible_brands: isomiso2avc1mp41
[ERROR] encoder : Lavf56.40.101
[ERROR] Duration: 00:01:00.12, start: 0.000000, bitrate: 887 kb/s
[ERROR] Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 480x600 [SAR 1:1 DAR 4:5], 833 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 59.94 tbc (default)
[ERROR] Metadata:
[ERROR] handler_name : VideoHandler
[ERROR] Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 48 kb/s (default)
[ERROR] Metadata:
[ERROR] handler_name : SoundHandler
[ERROR] Unknown encoder 'libfaac'
[ERROR]
```

Here the error:

```
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' 'video_source2.mp4' '-vf' 'movie=overlay_588a4d1b8e1e2.png [watermark]; [in][watermark] overlay=main_w - 0 - overlay_w:main_h - 0 - overlay_h [out]' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes588a4d1b98b20v107g/pass-588a4d1b98c20' 'export/masked_video.mp4'' in /home/saputrad/video.instamax.co/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /home/saputrad/video.instamax.co/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/local/bin...') #1 /home/saputrad/video.instamax.co/vendor/alchemy/binary-driver/ in /home/saputrad/video.instamax.co/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 168
```

I really curious what is the main problem?

Did I miss a step when giving an overlay image or I need convert the video source to a profile.
2 video which I use was come from Instagram that I downloaded before.

Thank you.

**Comment by Romain** [comment]
Hi @webfreaks,

I don't think that the size is a problem. I'm encoding files up to many Gb with PHP-FFMPEG without any problem.
From what I can see, the problem seems to be with your codecs: `Unknown encoder 'libfaac'`.

Could you tell me how you have installed FFMPEG on your server? Have compiled it using the compilation guide? 
https://trac.ffmpeg.org/wiki/CompilationGuide

If not, I would recommend that you follow this guide.

Also, have you tried to copy the command and paste it in your terminal to see if it works this way?

`'ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' 'video_source2.mp4' '-vf' 'movie=overlay_588a4d1b8e1e2.png [watermark]; [in][watermark] overlay=main_w - 0 - overlay_w:main_h - 0 - overlay_h [out]' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes588a4d1b98b20v107g/pass-588a4d1b98c20' 'export/masked_video.mp4'`

Could you paste here the result of this command?

Could you also paste your piece of code from the moment you're creating ffmpeg object to the moment you're saving your file?

Thanks
Romain

**Comment by webfreaks** [comment]
Hi,
Thank you for the response.

I installed FFMPEG from this source https://s3bubble.com/installing-ffmpeg-on-centos-6-6-in-usrlocalbin/.

And here piece my code.

```
$ffmpeg = FFMpeg\FFMpeg::create(array(
	    'ffmpeg.binaries'  => '/usr/local/bin/ffmpeg',
	    'ffprobe.binaries' => '/usr/local/bin/ffprobe',
	), $logger);

    $video = $ffmpeg->open( $video_path );
	
    $ffmpeg->getFFMpegDriver()->listen(new \Alchemy\BinaryDriver\Listeners\DebugListener());
 	$ffmpeg->getFFMpegDriver()->on('debug', function ($message) {
	    echo $message."<br>";
	});


	$video
	    ->filters()
	    ->watermark($watermarkPath, array(
	        'position' => 'relative',
	        'bottom' => 0,
	        'right' => 0,
	    ));

	$video_export_path = 'export/masked_video.mp4';
	$save = $video->save(new FFMpeg\Format\Video\X264(), $video_export_path);
```

Thank you.

**Comment by Romain** [comment]
Hi @webfreaks,

Thanks for this answer.

Like I said, I think that the problem comes from the fact that you don't have the codec aac installed. Following the compiling guide to install FFMPEG is the best way to prevent this.

However, I think there is a work-around.
Could you try to define the format of the exported video as follow:

```php
$format = new FFMpeg\Format\Video\X264();
$format->setAudioCodec("libmp3lame");
$save = $video->save($format, $video_export_path);
```

Let me know if this works for you.

Romain

**Comment by webfreaks** [comment]
Hi,

It's working like a charm :D.
Thank you for the help @Romain

**Comment by Romain** [comment]
You're welcome! ;)
