### ISSUE TITLE
Is it possible to use this without Composer?

### ISSUE THREAD

**Issue by fpolli** [PHP-FFMpeg/PHP-FFMpeg#382]
I by choice do not use Composer, and am having issues trying to get the library to work.

I tried  include("$codedir/FFMpeg/FFMpeg.php"); and it told me it could not find FFProbe class, so then I added an include for FFProbe, so beginning of code looks like this:

          include("$codedir/FFMpeg/FFMpeg.php");
          include("$codedir/FFMPeg/FFProbe.php");
          $ffmpeg = FFMpeg\FFMpeg::create();

Now it tells me:
Fatal error: Uncaught Error: Class 'Doctrine\Common\Cache\ArrayCache' not found in /.../FFMPeg/FFProbe.php:204 Stack trace: #0 /.../FFMpeg/FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, NULL) #1 /....php(98): FFMpeg\FFMpeg::create() #2 /....php(12): include('/...') #3 {main} thrown in /.../FFMPeg/FFProbe.php on line 204

Thank you

**Comment by jens1o** [comment]
No, it's not possible without getting your hands dirty. We have a bunch of dependencies that this wrapper actually works, and you would need to download every dependency and its sub-dependencies and the sub-sub-dependencies... And include every file to the running script. I'm afraid but I  think you can't do that, because it would need really long time.
