### ISSUE TITLE
[Question] Is it possible to ffmpeg from a stream resource (php) ?

### ISSUE THREAD

**Issue by kocoten1992** [PHP-FFMpeg/PHP-FFMpeg#468]
Hi guys,

I want to encode a file from distant (google drive), the file in bluray format, download the file and then encode is certainly an option but it rather slow, looking for a way to encode directly from online storage service (and possibly send it to another storage service, using stream).

Service like google drive can be downloaded using ```stream resource```, how can I map that to ffmpeg (using [pipe](https://ffmpeg.org/ffmpeg-protocols.html#pipe) in ffmpeg - possible ?).

You could tell me the idea, I'm gonna dig hard experimenting it (already try to mess with file descriptor in Unix, but no result yet).

Thank you.

**Comment by jens1o** [comment]
Hello! :)

This should not be done with this library, because a memory leak is going to come, because we store much information about the rendering process, because actually it is supposed to be used for short-living scripts. It should be used for hours, days, or even months without a restart of the php process.

The hole library is not compatible for using pipes, and it would be a big b/c break and at the moment, I'm restricted to use Windows, so I can not test it, while this is a key goal.

I'm sorry.

Perhaps you could dig in other wrappers, e.g. node.js. Thank you for interest.
