### ISSUE TITLE
FFMPEG Video Audio Masking

### ISSUE THREAD

**Issue by waqadeer** [PHP-FFMpeg/PHP-FFMpeg#477]
Hello FFMpeg writer

It look really great but I am here now going to mask a voice, that must be get from some text-to-speech API. To achieve this, what i am doing is

1. Prepare a text-to-speech audio by the logged in user's name
Any text-to-speech api. for now i am using ; `http://duncan3dc.github.io/speaker/`

2. Prepare and Audio (abc.mp3) that will be merged/mapped into the resulted video
`ffmpeg -i *mainVideo.mp4* -i *textToSpeechGetUserName.mp3* -filter_complex "[0:a]atrim=0:1,asetpts=PTS-STARTPTS[aud1]; [1:a]atrim=0:1,asetpts=PTS-STARTPTS[aud2]; [0:a]atrim=start=1,asetpts=PTS-STARTPTS[aud3]; [aud1][aud2][aud3]concat=n=3:v=0:a=1[aout]" -map "[aout]" -c:v copy *media/movie/result.mp3* 2>&1`

3. Create a video masked with the newly built audio
`ffmpeg -i *mainVideo.mp4* -i *media/movie/result.mp3* -map 0:v -map 1:a -c:v copy *media/result.mp4* 2>&1`

I want to make it using this library as putting the shell command into the code is not a good practice. 

OR I appreciate if you could suggest any other better and optimized solution.

Thanks a LOT!

**Comment by jens1o** [comment]
Hi,

thanks for creating such an issue. Unfortunately you need to work around with this, because it isn't supported to achieve exactly what you want to do. You can achieve this using SimpleFilters that will create and modify the command, so you can inject custom commands.
In case you have more questions, do not hesitate to ask.

Regards
Jens
