### ISSUE TITLE
Example and PHPDoc param signature mismatch for Concat

### ISSUE THREAD

**Issue by NinoSkopac** [PHP-FFMpeg/PHP-FFMpeg#529]
From README.md

```php
// In order to instantiate the video object, you HAVE TO pass a path to a valid video file.
// We recommand that you put there the path of any of the video you want to use in this concatenation.
$video = $ffmpeg->open( '/path/to/video' );
$video
    ->concat(array('/path/to/video1', '/path/to/video2'))
    ->saveFromSameCodecs('/path/to/new_file', TRUE);
```

Note how saveFromSameCodecs() implies the first param is a string?

Now look at PHPDoc for the same function: https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Media/Concat.php#L75 (expects an array)

**Comment by jens1o** [comment]
The problem here is, that the documentation is right, but the phpdoc is right. 

Perhaps the person implemented this had been confused with this line, where he is converting it internally into an array: https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/a1d5fa51ba94929c93e9a03dce16990d6ca177bc/src/FFMpeg/Media/Concat.php#L140
