### ISSUE TITLE
[Question] How to get progress from advancedmedia?

### ISSUE THREAD

**Issue by lloonnyyaa** [PHP-FFMpeg/PHP-FFMpeg#748]
I am opening multiple video files for processing via `openAdvanced()`
Here's some sample code:
```php
$ffmpeg = FFMpeg::create();
$format = new X264;
$format->setAudioCodec("aac");

$video = $ffmpeg
    ->openAdvanced([$input1, $input2]);

$video
    ->filters()
    ->custom('[0:v][1:v]', $filter, '[out]');

// listener
$format->on('progress', function ($video, $format, $percentage) {
    echo $percentage;
});

$video
     ->map(['[out]', '1:a'], $format, $fileName)
     ->save();
```

The `progress `event does not work in this case.

I can see from the [code](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Media/AdvancedMedia.php#L217) that the data for this event is hardcoded in `AdvancedMedia`.
But maybe there are some options to get a percentage of progress? Maybe I didn't see something ...

**Comment by CaliforniaMountainSnake** [comment]
ProgressListener only works fine with single input, single file, because the listener calculates the progress from the current size of the file.

If you have multiple complicated inputs, ffmpeg just doesn't provide any possibilities to calculate progress accurate.
So, AdvancedMedia set standard progress listener for the first input, but it is not accurate.
